version: '3'

services:

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - "/application_stack_data/redis:/data"
    
  web:
    image: localhost:5000/flask-redis-app:latest
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - redis
